/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VisualTreeComponent } from "./components/visual-tree/visual-tree";
export namespace Components {
    interface VisualTreeComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLVisualTreeElement extends Components.VisualTreeComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLVisualTreeElement;
        new (): HTMLVisualTreeElement;
    };
    interface HTMLElementTagNameMap {
        "visual-tree": HTMLVisualTreeElement;
    }
}
declare namespace LocalJSX {
    interface VisualTreeComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "visual-tree": VisualTreeComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "visual-tree": LocalJSX.VisualTreeComponent & JSXBase.HTMLAttributes<HTMLVisualTreeElement>;
        }
    }
}
